apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.cee.redhat.com/rhel-lightspeed/roadmap/frontend/-/tree/{{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push"
      && target_branch == "main"

  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: roadmap-frontend
    appstudio.openshift.io/component: roadmap-frontend
    pipelines.appstudio.openshift.io/type: build

  namespace: rhel-lightspeed-tenant
  name: roadmap-frontend-on-push

spec:
  params:
    - name: git-url
      value: '{{ source_url }}'

    - name: revision
      value: '{{ revision }}'

    - name: output-image
      value: quay.io/redhat-user-workloads/rhel-lightspeed-tenant/roadmap-frontend:{{ revision }}

    - name: dockerfile
      value: Dockerfile

    - name: path-context
      value: .

    - name: additional-tags
      value:
        - latest
        - '{{ target_branch }}'

  pipelineRef:
    name: pipeline-build

  taskRunSpecs:
    - pipelineTaskName: sast-coverity-check
      stepSpecs:
        - name: build
          computeResources:
            requests:
              memory: 8Gi
            limits:
              memory: 8Gi

        - name: postprocess
          computeResources:
            requests:
              memory: 8Gi
            limits:
              memory: 8Gi

  taskRunTemplate:
    serviceAccountName: build-pipeline-roadmap-frontend

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
