apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.cee.redhat.com/rhel-lightspeed/digital-roadmap/digital-roadmap-frontend/-/tree/{{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push"
      && target_branch == "develop"

  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: digital-roadmap-frontend-develop
    appstudio.openshift.io/component: digital-roadmap-frontend-develop
    pipelines.appstudio.openshift.io/type: build

  namespace: rhel-lightspeed-tenant
  name: digital-roadmap-frontend-push

spec:
  params:
    - name: git-url
      value: '{{ source_url }}'

    - name: revision
      value: '{{ revision }}'

    - name: output-image
      value: quay.io/redhat-user-workloads/rhel-lightspeed-tenant/digital-roadmap-frontend:{{ revision }}

    - name: dockerfile
      value: Dockerfile

    - name: path-context
      value: .

    - name: additional-tags
      value:
        - latest
        - '{{ target_branch }}'

  pipelineRef:
    name: pipeline-build

  taskRunSpecs:
    - pipelineTaskNmae: sast-coverity-check
      stepOverrides:
        - name: build
          computeResources:
            requests:
              memory: 2Gi

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'

    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null

        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 1Gi
